### ISSUE TITLE
Appending slash in the Uri getPath

### ISSUE THREAD

**Issue by harikt** [phly/http#22]
For a url `http://localhost:8000/admin` , it appends `/admin/` as the path. Which makes the routes to fail for the routes are defined only for `/admin`

```php
<?php
$path = $request->getUri()->getPath();
```

**Comment by harikt** [comment]
By the way I only have the problem with `/admin` url. The other url like `/login` don't have any trouble.

Wonder :-/ .

**Comment by weierophinney** [comment]
I've not observed this, and cannot reproduce it. If you can reproduce it, open a PR with a test case.

**Comment by harikt** [comment]
@weierophinney I have noticed it in conduit , will open there :) .

**Comment by harikt** [comment]
Here you go https://github.com/phly/conduit/pull/25
