### ISSUE TITLE
fpassthru stream() instead of `echo` in Server::send()

### ISSUE THREAD

**Issue by sasezaki** [phly/http#38]
Hi, @weierophinney . 

Is there not preferable using fpassthru() for low memory usage ?
in Server's send() method.
https://github.com/phly/http/blob/master/src/Server.php#L177

eg.
``` php
<?php
$stream = $response->getBody()->detach();
rewind($stream);
fpassthru($stream);
// or stream_copy_to_stream($stream, fopen('php://output', 'wb+'))
```
current `echo $response->getBody()` calls __toString & stream_get_contents().

Is there any thought about current  `echo $response->getBody()` implementation ?

**Comment by weierophinney** [comment]
I've actually benchmarked, and found that fpassthru was slower in the majority of use cases, by > 20%. I think PHP has some optimizations around `echo` with regards to streams.

**Comment by sasezaki** [comment]
I see.
So, does Phly\Http\Server  not assume attaching big size ( memory_limit over) stream ?
