### ISSUE TITLE
Uri object can't be serialized 

### ISSUE THREAD

**Issue by dzentota** [phly/http#53]
I want to store Request objects in the db, so I have to serialize it. Request internally uses Uri.
serialization of Uri fails with error "Serialization of 'Closure' is not allowed ". Could you add a method for urlencoding url fragments instead of assigning Closure to $urlEnode?

```php
<?php
$uri = new Phly\Http\Uri('http://google.com/foo/bar');
serialize($uri);

**Comment by sasezaki** [comment]
@dzentota Are you think Stream could be serializable as object ?

**Comment by sasezaki** [comment]
Requesting `implements toString()` - represent HTTP Message as string. (like. 
https://github.com/zendframework/zf2/blob/master/library/Zend/Http/Request.php#L525 ) makes sense than serializing.

**Comment by dzentota** [comment]
@sasezaki don't get what are you talking about. I've already fixed this issue and provided a pull request
