### ISSUE TITLE
again about returning clones

### ISSUE THREAD

**Issue by pine3ree** [phly/http#58]
HI @weierophinney ,

i noticed that in case of no state change you still return a cloned instance:
```php
// ex. Uri::withScheme(...)
// Do nothing if no change was made.
return clone $this;
``` 
In my opinion (i wrote/asked about this somewhere else) since the instance does not change we could simply return $this. This does not affect immutability.

I missed this point (basically what i was asking about and i never noticed, or maybe it was added later) before in the specs but:
https://github.com/php-fig/fig-standards/blob/master/proposed/http-message-meta.md 
paragraph : New instances vs returning $this

seems to approve returning just $this.

**Comment by weierophinney** [comment]
Yes, we made that change to the specification. Note that it says MAY; it's not a requirement to return `$this` in such situations.

I didn't revert the changes I made with the latest version, because of that MAY; it's not required. In my testing and usage, there are very few cases where such a condition would trigger, which makes it a micro-optimization at best. Considering that the heavy lifting of filtering/normalizing values has to occur before any such condition checking, I'm not convinced that the change is required.

**Comment by pine3ree** [comment]
@weierophinney 
yeah, i know. It's a fixation of mine that comes from economic picking in guitar playing: "don't do any movement unless you really need to". So to me, even if an operation does not cost so much, it's always preferable not doing it unless it's really needed. 
In this case "we" are returning an immutable clone of something that's immutable. So why not just return that something. In my mind, using simple variables,  i see it like this:
```php
/...
$a = 10;
//...
if (!$doubleIt)  {
    return $b = $a;
} 

return 2 * $a;
```

even if the assignment doesn't cost, i would never do that, i would simply return $a;
But that's just my point of view.

Before closing the discussion, any reason to keep members (like $queryParams, $attributes in ServerRequest) private in your http-message implementation? It would make life easier to be able to do something with them in an overridden constructor...

best regards
maks

**Comment by weierophinney** [comment]
@pine3ree —

> "don't do any movement unless you really need to". So to me, even if an operation does not cost so much, it's always preferable not doing it unless it's really needed.

One concern I look at, though, is complexity. Adding _any_ conditional into a method increases complexity, and requires additional test cases to ensure behavior is as expected for the new execution paths. As such, there's a *maintenance cost* to the operation. As a developer, I have to weigh both. I've chosen to reduce the complexity to ease maintenance.

> any reason to keep members (like $queryParams, $attributes in ServerRequest) private in your http-message implementation?

Marco Pivetta (@Ocramius) has convinced me over the years that it's the onus of users to provide concrete use cases for loosening visibility. By declaring the members private to begin with, users can be assured that operations will work as specified, even in class extensions; if they are protected or public, it's possible the extension is altering the behavior in unexpected ways. As such, keeping them private is ideal, *until a demonstrated, general-purpose use case is presented*.

If you need to read or alter private properties, Marco has blogged on how to do so: http://ocramius.github.io/blog/accessing-private-php-class-members-without-reflection/

**Comment by pine3ree** [comment]
@weierophinney 
Hello Matthew, Thank You for answering.

1) I agree with you about complexity.The  "don't do any movement unless" phylosophy also embraces simplicity.
In these particular cases (my example and the cloning of $this), since we already use a (simple) condition:
```php
$a = 10;
// 1.
if (!$doubleIt)  {
    return $b = $a; // return clone $this
} 
// 2.
if (!$doubleIt)  {
    return $a; // return $this
} 

return 2 * $a;
```
implementation 2 looks simpler than 1 (...and since messages are immutable returning $this wouldn't hurt)

Anyway i don't want to be a pest anymore about it, so I'll stop asking.

2) Thanks for the tip, i've used closure object binding before...it didn't came to my mind for this.
I understand keeping properties private is beneficial, especially in a weakly typed programming language and when a class could be used and extended by many people introducing unexpected behaviour. That said, ont thing that i miss in the server request implementation i single parameter access (as in getAttribute()), st like:
```php
$user_id  = (int) $request->query('user_id', 0); // 0 as default
$username = $request->data('username', ''); // '' as default
$remember = (bool) $request->cookie('remember', false);
```
I guess the Interface would become too cluttered with all specific single-accessor methods.
The only reason i asked is that I also don't like to implement those accessor calling a method to retrieve all the parameters to get one. But, as already said, I understand your choice and kind of expected the same reason for it.

best regards

**Comment by weierophinney** [comment]
@pine3ree —

> ont thing that i miss in the server request implementation i single parameter access (as in getAttribute()),

You could write your own extension methods in a decorator, which is actually very easy to accomplish when using PHP 5.4 and above (due to the ability to deference arrays on access):

```php
use Phly\Http\ServerRequest;
use Psr\Http\Message\ServerRequestInterface;

class Request extends ServerRequest implements ServerRequestInterface
{
    private $request;

    public function __construct(ServerRequestInterface $baseRequest)
    {
        $this->request = $baseRequest;
    }

    /* implement override methods for all public methods in ServerRequest
     * that simply `return $this->request->{method name}(args)`
     */

    public function getQuery($name, $default = null)
    {
        if (! isset($this->getQueryParams()[$name])) {
            return $default;
        }

        return $this->getQueryParams()[$name];
    }
}
```

You can simplify the creation using something like [ProxyManager](https://github.com/Ocramius/ProxyManager).

As you note, we didn't provide accessors for single values in order to keep the interfaces more slim, and I did not provide additional methods outside the interfaces deliberately, in order to get people familiarized with the PSR-7 specification proper. In PHP 7, such methods will essentially be unnecessary with the coalesce operator, as you'll be able to do this:

```php
$userId = (int) ($request->getQueryParams()['user_id'] ?? 0);
```

which is quite succinct.

**Comment by pine3ree** [comment]
Yes, thank You. that's how I actually implemented the single accessor methods inside my descendant (i didn't need to implement a decorator since i only needed to add, and as you pointed out, psr-7 interfaces and your implementation will stay that slim).

php-7 one line call looks very useful....anyway...until we will be using (...and getting used to use) it
```php
function ($request, $response) {
    $userId = (int) $request->getQuery('user_id', 0);
    //...
}
```
still looks prettier and more coincise...(personally, i also prefer getter syntax to array access)

PS
please don't answer back! ...you'll risk I'll add something more that will waste more of your time :-).
