### ISSUE TITLE
No issue, just a question

### ISSUE THREAD

**Issue by pine3ree** [phly/http#61]
Hi @weierophinney 

shouldn't be better to have $allowedSchemes as a static property?
maybe also add a '' => null key-value pair?

kind regards

**Comment by weierophinney** [comment]
> shouldn't be better to have $allowedSchemes as a static property?

Why? To allow adding schemes? or...? The problem with making it static is that it could be overwritten with garbage values. If the ability to use custom schemes is something you want, that can be accommodated in other ways; let me know if that's what you want.

> maybe also add a '' => null key-value pair?

Why? What's the use case?

**Comment by pine3ree** [comment]
Hello @weierophinney ,

no, what i meant is that allowedSchemes should be a class property not an instance property, since all the instances should allow either http or https (or empty) scheme name or, in other words, the validity of a scheme name should not be related to a single instance but to URIs in general. I was thinking it still as a protected property. If a new scheme is allowed, shouldn't it be still class-related (even if only for a subclass) and not for a single instance. For example Josh codeguy in slim 3 also uses a static variable in a method to validate (filter) the scheme name before assigning it. In your same implementation there  is  - rightfully - no way (not even in the constructor)  to assign different instance values to the allowedSchemes array, because it's simply used as a constant-like property for scheme-name validation.

Forget about my second comment: it could make sense because an empty string is a valid scheme for the interface (as codeguy did), but it doesn't make sense to associate it with a port value (and you use the hash-map to determine if it has a standard port, not just the keys as slim-3 implementation)

kind regards
