### ISSUE TITLE
Inconsistent output buffering

### ISSUE THREAD

**Issue by mtymek** [phly/http#71]
`Server::listen` is responsible for starting output buffering...

```php
public function listen(callable $finalHandler = null)
    {
        $callback = $this->callback;
        ob_start();
        // ...
    }
```

...while it is flushed in `SapiEmiter::emitBody`:

```php
private function emitBody(ResponseInterface $response, $maxBufferLevel)
    {
        if (null === $maxBufferLevel) {
            $maxBufferLevel = ob_get_level();
        }

        while (ob_get_level() > $maxBufferLevel) {
            ob_end_flush();
        }

        echo $response->getBody();
    }
```

For consistency (=easier consumption of `phly/http` library), responsibility for output buffering should be placed in only one of this two classes.

Because of this, after upgrading PHPUnit (v4.6.*), you will see following error:

```
Test code or tested code did not (only) close its own output buffers
```

**Comment by weierophinney** [comment]
Oops! I meant to remove that from listen(). I'll work on a patch shortly.

**Comment by weierophinney** [comment]
Interestingly, tests still pass under 4.6; it's just that several are marked as "risky". :) Will see if I can fix them.

**Comment by mtymek** [comment]
Removing `ob_start` from `Server::listen` makes them pass without any warning. I could send a PR myself, but I'm not sure what's your idea of dealing with output buffer.

**Comment by weierophinney** [comment]
@mtymek well, the idea is that I want output buffering enabled in the `Server`. I've altered the code locally to pass the buffer level on to the emitter, but it's not making a difference with the tests. Still researching.

**Comment by weierophinney** [comment]
Figured out the issue; the code flushes to the current level at the time invoked. Since `Server` calls `ob_start()`, when we're in a unit test, that's nested. As such, the tests need to call `ob_end_flush()` to ensure that PHPUnit sees the output.

**Comment by mtymek** [comment]
Isn't it just a workaround? If you remove ob_* from Server class, you won't need to add quirky code to unit tests at all.

**Comment by weierophinney** [comment]
@mtymek Again, I *want* the output buffering in the Server class; that class is running the various middleware. Think of it like a front controller.

**Comment by mtymek** [comment]
Ah, in first comment you mentioned removing them from `listen` method, I thought you also meant removing them from the whole class. But it means that we still have inconsistency, as buffering is started in Server and flushed in Emitter.

**Comment by weierophinney** [comment]
> But it means that we still have inconsistency, as buffering is started in Server and flushed in Emitter.

Nope. I'm passing the ob_level to the emitter *from* the server; the emitter will only flush to that level. I'd just forgotten to do that previously, even though I'd built that argument into the emitter (this patch implements passing the argument).

**Comment by mtymek** [comment]
I still think it should be abstracted somehow. Imagine using it in React PHP - style application, where you send output in completely different manner, and echo's are used for debugging output. So, IMO it should be fully handled by the emitter.

**Comment by weierophinney** [comment]
@mtymek I know the current approach works with SAPI environments, and is well-tested (both in unit tests and in production). I've not played with React at this point. If you can provide a patch that works against both, feel free to submit it. But I will need more than "I still think..."; I need demonstration at this point.

**Comment by mtymek** [comment]
Clear. I will prepare working example and then get back to you.
